// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svwprqjulmijwyvdikwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2d3BycWp1bG1pand5dmRpa3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MjEzODMsImV4cCI6MjA2MzI5NzM4M30.xa2w9qtmRmtvtWaH-w051M4Li_Y79_eBJYnLJGcJoA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);